name = "Eoshifts"
uuid = "a610e8d0-bcf9-11f0-bd78-7b325b0dfb67"
authors = ["William Herrera <wherrera@alahonua.com>"]
version = "0.1.2"

[compat]
julia = "1 - 2"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
